forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-puppetdb', "4.0.0"
mod 'hunner/hiera', :git => "https://github.com/benjamink/puppet-hiera.git"
mod 'iverberk-puppet-infra', :git => "https://github.com/iverberk/puppet-infra.git"